### ISSUE TITLE
Feature Request: IronFormBehavior

### ISSUE THREAD

**Issue by coreyfarrell** [PolymerElements/iron-form#145]
This custom element does not contain any template markup, most or all of it can be moved to a behavior.  This could be done in a non-breaking way and would make this code more useful.  The main use case is to import form behaviors into a custom app-form which provides consistent layout of forms for an app - Save/Cancel always in the same place, overflow scrolling of a specific area, etc.

Before working on a patch I'd like to get some guidance.  Is this something that would be accepted?  Do we want a single behavior for everything that is iron-form?  Another option might be a behavior to handle iron-form-element registration and serialization with a separate one to handle network interactions.

**Comment by notwaldorf** [comment]
This element is a type extension of an html `<form>` element -- so it inherits all the functionality of the native element. Because of this, it cannot have a template, since you're not allowed to add a shadow root on native elements.

If you just create a behaviour, then you will lose all the native functionality of a `<form>` element (such as autosubmitting the form when clicking an `<input type=submit>` button, etc. 

If you're doing this just to get a consistent layout, then I suggest just making your own element -- I think it's unlikely we'll merge it here, since form layout varies greatly from use case to use case. However, having that element will be beneficial to a lot of people! Make sure you set the right keywords in `bower.json` so that it shows up on https://customelements.io/.

Let me know if I misunderstood this question!

**Comment by coreyfarrell** [comment]
Didn't realize native elements can't have shadow root.  My idea can still be useful, but not as much as I thought.  The idea is for 'iron-form' to be almost empty, to simply import the behavior(s) containing the current code.  So iron-form.html JavaScript would look like:
```
Polymer({
  is: 'iron-form',
  extends: 'form',
  behaviors: [
    Polymer.IronFormBehavior
  ]
});
```

Right now I'm unsure the best break-down of IronFormBehavior (composite behavior or not).  The goal is that I could create my own element that would import the behavior then extend / override as needed.

**Comment by coreyfarrell** [comment]
Where can I see the standard that shadow root is not allowed on native elements?  I actually do have my own Polymer element that `extends: 'form'`, and it has a template.  The template if fully functional with and without shadow DOM enabled (tested with Chrome 51 on Fedora 23 x86_64).  Verified with Element Inspector that shadow root is in the form element and that the form element has standard native methods that come with HTMLFormElement.

So am I using a feature that has very poor support among other browsers, or is it a bug that Chrome 51 with webcomponents-lite.js is allowing this to work?  Does it make a difference that <form> is expected to have child nodes where img or br should not?

**Comment by notwaldorf** [comment]
Here's the spec section that addresses this: https://www.w3.org/TR/shadow-dom/#methods. <form> isn't on that list, so you cannot attach a shadow root to it. The fact that you might be able to do it just means Chrome hasn't added all the checks it needs to (since the spec was in limbo until recently). In any case, it should not be supported.

**Comment by coreyfarrell** [comment]
That's very disappointing, does not make sense to prevent use of shadow root in elements where content makes sense (a form is a container).  For now I have to focus on reworking my own form element since apparently it's using features that will stop working.  I don't know what to do with this request so I'm just going to close it for now.
