### ISSUE TITLE
Why trigger the native browser invalid-form UI?

### ISSUE THREAD

**Issue by rbjarnason** [PolymerElements/iron-form#15]
Why trigger the native browser invalid-form UI here?
https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L99

Any way to turn this feature off?

Thanks for all the great elements :)

**Comment by notwaldorf** [comment]
Is there a reason why you don't want it? I could add a property so that you can explicitly disable it, but the problem is that if we don't trigger the native invalid UI, then native elements inside the form won't look "invalid" (it's not just the popup "fill this in" bubble, it's also the red outline on elements).

**Comment by ernestoalejo** [comment]
Don't know OP reasons but I found this issue searching for a way to make a paper-input required without using browser bubbles for errors.

**Comment by rbjarnason** [comment]
Here is a screenshot of the native validation I'm talking about. Two problems, its not material design and its in English in an otherwise Icelandic only website.

I could not use required but this causes the element not being validated at all. 

![nativewarning](https://cloud.githubusercontent.com/assets/43699/8167964/1b25807c-1391-11e5-80b7-9f08487ecf7c.png)

**Comment by notwaldorf** [comment]
Oh you can set the error message if you want (`setCustomValidity('I am a custom message'`). I agree it's not material -- it's implemented by the browser.

I am worried about removing it by default (because you will get no UI for native elements), but I will add a property so that if you really want this, you can turn off the native vaidation UI. Sounds good?

(should be in by end of the week at the latest)

**Comment by rbjarnason** [comment]
I understand the reason regarding native elements. Solution sounds good @notwaldorf :)

**Comment by rbjarnason** [comment]
Thx @notwaldorf :) This solves the problem for me.  One belated idea, what about disabling this behavior automatically when there are no native elements?
