### ISSUE TITLE
iron-form does submit on ENTER with paper-input and shadow dom

### ISSUE THREAD

**Issue by dbrans** [PolymerElements/iron-form#189]
### Description
When shadow dom is enabled, pressing ENTER in a paper-input will not submit the form.

This demo (submit on ENTER) does not work with shadow DOM enabled:
https://github.com/PolymerElements/iron-form/blob/master/demo/index.html#L118

### Expected outcome
Submit on ENTER should work with shadow dom.

### Actual outcome
ENTER has no effect when shadow dom is on.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
This is a browser bug. Basically the `<form>` does not see the nested `<input>` inside the `paper-input`'s shadow root, and can't  set up the magic "enter" listener. Fixing this would be kind of horrifying (in the `iron-form` add some form of global "keydown" event that tracks `Enter`, and then submit the form?), so I don't think we should do it, and just accept it as a limitation of `iron-form`

If this is a super important feature for you, since you control which elements you put in the form, i recommend detecting the Enter key from them, and calling `submit` yourself.
