### ISSUE TITLE
Validate Without Requiring `require`

### ISSUE THREAD

**Issue by zikes** [PolymerElements/iron-form#43]
https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L243

The `if` only validates a custom element if it's `require`d, but fields may simply have a `pattern` or other validation.

**Comment by notwaldorf** [comment]
Yup, you're right, this is totally a thing the platform does. Would you be interested in sending a PR for that? :)

**Comment by zikes** [comment]
That sounds fun! I'll give it a go.

In case anyone else gets to it before me, the offending LOC is now at https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L329

**Comment by chiefcll** [comment]
Submitted a fix - wondering if there will be a release.

**Comment by akc42** [comment]
I am confused by all these references.  I assume the offending line of code is moving due to other changes, as I see the problem today as at here

https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L378

My use case is a search form, where users may or may not type input into some selection fields.  If they do provide input I want to validate it, but of they don't then I don't want form validation to fail.

An example which demonstrate this is 

http://jsbin.com/hucomi/edit?html,console,output

**Comment by notwaldorf** [comment]
There's a PR out to fix this: https://github.com/PolymerElements/iron-form/pull/125
