### ISSUE TITLE
What if custom _getValidity method needs to make an Ajax request?

### ISSUE THREAD

**Issue by jab** [PolymerElements/iron-form#57]
https://github.com/PolymerElements/iron-form/blob/master/demo/simple-element.html demonstrates an element with a custom _getValidity method.

Let's say you have a `<paper-input type="email" required auto-validate>` in your iron-form. But it needs customized _getValidity logic because once the client-side has determined it's a valid email address, it has to ask the server if the email address is already in use. This requires an Ajax request. But _getValidity isn't allowed to return a promise, it must return true/false. Are you meant to block on the Ajax request (bad practice?), or should the _getValidity API accommodate this some other way?

Thanks for any tips and for the great work on Polymer.

**Comment by jab** [comment]
![screen shot 2015-10-04 at 16 24 19](https://cloud.githubusercontent.com/assets/64992/10270039/67004656-6ab4-11e5-9dc7-d5eb175d68e0.png)

**Comment by notwaldorf** [comment]
I don't think this is a thing we will support. `iron-form` is just an extension of the native `form` element, so that it works with custom elements. A native form wouldn't let you override the validation of any of its elements and you would have to end up doing something like:
- user presses a submit button, which calls a `presubmit()` method
- the `presubmit()` method does custom validation of the form (including this ajax request)
- if everything works out and the form is valid, do the actual submission.

In particular, `_getValidity`, returns whether an element is valid, and can't do any async calls (what would that mean? it can't be sync and block, since that's a terrible experience, and otherwise, how would it tell the form that it's decided on the validity?). If you don't want to do this presubmit-and-validate method I described above, you could have a custom `onBlur`handler, that does this async validation and sets a boolean inside your custom element, that `_getValidity` can access when called.

**Comment by notwaldorf** [comment]
(you can also do your async validation on an `input` or `change` event too)
