### ISSUE TITLE
<form class="layout vertical" is="iron-form" breaks safari

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/iron-form#65]
demo http://gcl-12.appspot.com @cdata

**Comment by notwaldorf** [comment]
I don't see you including `iron-flex-layout` anywhere, or `webcomponents.js` (to be fair, with all the minimized/vulcanized stuff, I can't really follow what's going on in your `<head>` section).

Here's a jsbin that adds both `layout horizontal` and `layout vertical` to forms, with the correct includes, and it works fine on all the browsers: http://jsbin.com/huyuxi/1/edit?html,output

Screenshot from safari:
<img width="833" alt="screen shot 2015-10-19 at 12 47 35 pm" src="https://cloud.githubusercontent.com/assets/1369170/10589398/fe2acb8a-765f-11e5-934b-abe5bf6c10f6.png">

Please re-open this if you can repro your issue in a jsbin, or have more details about what's going on. I think either some of your imports are wrong, or you've got some styles being applied incorrectly.

**Comment by gertcuykens** [comment]
Ps but you can see the difference between Chrome and Safari right in the demo?
@cdata on slack took a look first and could reproduce and asked to make a ticket for this.

**Comment by notwaldorf** [comment]
I can see a difference in your demo, yes, but I also can't really debug your code, since everything is vulcanized, resulting in 25k lines of code. Also, I see a bunch of alarming things in your code, like typos:
```
<form id="brm" class="layout vertical" style="padding:10px" is="iron-form" methode="POST" action="/mail.go" on-iron-form-response="formResponse">
```
(should be `method` not `methode`)

I also see that in some of your elements (like `brm-form`) you're using shadow styling, which is not supported on Safari. For example,
```
paper-checkbox::shadow #ink {color: #4285f4;}
```

Also, again, I can't tell if you're including `iron-flex-layout` in the actual file that you're using it, making it it almost impossible for me to debug this. It would be great if you could get a smaller snippet of code to reproduce, otherwise there isn't much I can do here (especially since in the jsBin I attached, the style is working fine)

**Comment by notwaldorf** [comment]
I'm also a bit worried that this including-everything-in-a-script might cause some timing issues as well.

**Comment by gertcuykens** [comment]
But vulcanise did that `including-everything-in-a-script` for me? Anyway I will try to strip it more and leave it unvulcanized.
