### ISSUE TITLE
demonstrate reacting to form's submitted state changes

### ISSUE THREAD

**Issue by jab** [PolymerElements/iron-form#68]
Ajax forms transition between submitted states like this:
not submitted → submitted / request in flight → (response received, so back to) not submitted

A common UI pattern is to disable the submit button and change its text from "submit" to "loading..." (show a spinner, etc.) while the request is in flight.

An iron-form is submitted via an internal iron-ajax element. iron-ajax has a "loading" property for whether a request is in flight. Does iron-form expose this property so the pattern above can be expressed simply? Or do we have to duplicate the logic that keeps track of the "loading" state on the form itself?

Would you consider demonstrating this pattern in the iron-form demo page to show off the recommended way to do this? Thanks for your consideration.

**Comment by notwaldorf** [comment]
This is technically done in the demo -- the page listens to `iron-form-submit` and updates a status message (https://github.com/PolymerElements/iron-form/blob/master/demo/index.html#L133). You could do this by also listening to `iron-form-presubmit`, or `iron-form-response` (when a response is received from the server).

As of a recent R, the `iron-ajax` object used by the form has been exposed as a public property, so you can listen to it as well.

I don't think this can be done successfully for the demo, since we don't actually have a server, and we receive a 404 response pretty immediately. Also, the demo is meant to be a quick demonstration of how the form works, and not of an entire app relying on it

/cc @arthurevans @robdodson, as they might have some thoughts on this (maybe do a larger demo/tutorial etc we can link to).

**Comment by jab** [comment]
Thanks for responding @notwaldorf! On the go and may write more later but just wanted to point you toward httpbin.org -- have you seen the /delay endpoint? e.g. http://httpbin.org/delay/3 -- looks like it could be pretty easy for the demo to use that to demonstrate this pattern.

**Comment by jab** [comment]
Hi @notwaldorf, just submitted a PR (#73) with a first pass at this. Here is a screenshot:
![screen shot 2015-10-30 at 20 11 47](https://cloud.githubusercontent.com/assets/64992/10860689/92f1e47a-7f42-11e5-9951-8c511f91e49c.png)

The first form now submits to http://httpbin.org/delay/2, giving the user 2 seconds to notice the form reacting to the submitted state change, which shows a spinner inside the submit button and disables it until the response is received. (Note I had to listen for `iron-form-submit` rather than `iron-form-presubmit`, since the presubmit event is fired before the `_setLoading(true)` call happens in the iron-ajax element.)

Now that I have a proof of concept, I'm wondering if there is a simpler, more reusable, or more flexible way to achieve this that you would recommend. For example, it would be super nice to be able to say something like:
```html
<paper-button loading-disable loading-spinner loading-text="Loading...">Submit</paper-button>
```
Where
- `loading-disable` would cause the button to be disabled,
- `loading-spinner` would show an (already added for you) spinner, and
- `loading-text` would change the "Submit" text to "Loading..."
while the iron-ajax is loading. (The user could opt into as many or as few of those as desired.)

What do you think?

**Comment by jab** [comment]
(I split that off into #77 since it's a separate issue)
