### ISSUE TITLE
serialize() method fails to toggle "on" values of <paper-toggle-button>

### ISSUE THREAD

**Issue by maria-le** [PolymerElements/iron-form#78]
`<iron-form>.serialize()` method returns `<paper-toggle-button>` values `"on"` when user toggles to `"off"`.

## Expected outcome
`<iron-form>.serialize() == {"foo":"off"}`

## Actual outcome
`<iron-form>.serialize() == {"foo":"on"}`

## Steps to reproduce
[See this Stack Overflow question](http://stackoverflow.com/questions/33581326/polymer-1-x-paper-toggle-botton-value-doesnt-toggle-off).

## Demo
[See this JSBin for the code](http://jsbin.com/ruzuwaqiyi/edit?html,output).

**Comment by srikkbhat** [comment]
I think this element should serialize `true` / `false` rather than value.

**Comment by maria-le** [comment]
Agreed. That suggestion should at least be discussed and decided.

It's now a new issue.

**Comment by srikkbhat** [comment]
Iron from will serialize `value` of on/off elements only if it is on. 
https://github.com/PolymerElements/iron-form/blob/v1.0.11/iron-form.html#L368

You can configure that value to anything you want. Say instead of `on` if you want the name of a color e.g. `orange` then you can set it. 

The issue with paper toggle is that it needs to have a role of 'radio' or 'checkbox' for it to have the above behavior. Its role is configured as button. So the value is serialized irrespective of whether it is on or off.
https://github.com/PolymerElements/iron-form/blob/v1.0.11/iron-form.html#L349

My request is to serialize the `checked` state instead of value.

**Comment by bicknellr** [comment]
Dupe of PolymerElements/paper-toggle-button#66, which is fixed.

**Comment by ankitkante** [comment]
@srikkbhat  I am still confused. When `iron-form` is serialized, I want the serialized value of `paper-toggle-button` to be `true`.How can I achieve this? Currently,it is serialized as `on`.

**Comment by bicknellr** [comment]
Set the [`value`](https://github.com/PolymerElements/iron-checked-element-behavior/blob/c3c6cf6038ea246c6952bbd46fb79cc70ea5fd16/iron-checked-element-behavior.html#L57) to the string you would like [iron-form to use when serializing](https://github.com/PolymerElements/iron-form/blob/b31d225737ebb2406f60c70d9a6c8bfff91b3fab/iron-form.html#L380).

**Comment by ankitkante** [comment]
Hi
Thank you for replying. Is there any way to set the attribute `value` to Boolean `true` instead of the string `"true"`?
