### ISSUE TITLE
events does not provide access to the response object

### ISSUE THREAD

**Issue by eximius313** [PolymerElements/iron-form#83]
Events ```iron-form-error``` and ```iron-form-response``` don't provide access to the ```event.detail.response``` object.
While ```iron-form-error``` doesn't have it at all (it allows access only to the request), in ```iron-form-response``` ```event.detail.response``` is set to null.

**Comment by Typel** [comment]
I think I've independently run into the same issue. Using both `get` and `post` methods, `event.detail.response` always returns `null`.
To verify that everything else was successful, response also includes:
`event.detail.response: null`
`event.detail.aborted: false`
`event.detail.errored: false`
`event.detail.status: 200`
`event.detail.statusText: "OK"`
`event.detail.timedOut: false`
`event.detail.succeeded: true`

iron-form is being submitted to a PHP script which simply echo's "Hello World".

Further details at [StackOverflow](http://stackoverflow.com/questions/33701018/how-to-submit-polymer-forms-to-php-and-display-response)

**Comment by Typel** [comment]
This issue does not appear to affect `json` content types, which work normally.
I tested `text` and `html` content types and both returned `null` instead of the expected output.

DOCTYPE='application/json', iron-form.contentType='json' => non-null
DOCTYPE='text/plain', iron-form.contentType='text' => null
DOCTYPE='text/html', iron-form.contentType='html' => null

**Comment by cogero** [comment]
I have the same problem, could you please fix this issue

**Comment by breloczek** [comment]
+1

**Comment by albin-pawel** [comment]
same here ... +1

**Comment by jkosioreklemonsky** [comment]
+1 for response object for text/html

**Comment by eximius313** [comment]
@rictic are there any chances of resolving this issue? I'd really appreciate this.

**Comment by jaromircelejewski** [comment]
hi,
any progress in solving this issue?

**Comment by AndyTyurin** [comment]
I tested on JSON, it returned null.

**Comment by rictic** [comment]
Hm, I'm having trouble reproducing this issue. Usually when response is unexpectedly null that's because the underlying `iron-ajax` has been configured to parse the response as JSON, but the response wasn't legal JSON. In that case the web platform is specced to set `response` to `null`.

Here's a repro case, comment out the handleAs line to see the response parsed as raw text rather than json: https://jsbin.com/mijuxocuho/edit?html,output

**Comment by eximius313** [comment]
@rictic It works for you because https://httpbin.org/get?name=hi2 returns JSON.
as @Typel [stated](https://github.com/PolymerElements/iron-form/issues/83#issuecomment-159457593) - in this particular case it works, but it does **not** work neither for ```text``` nor ```html```.
```iron-ajax``` should support not only JSON responses, so please reopen this issue.

**Comment by rictic** [comment]
It works for response types other than JSON, you just have to tell the underlying iron-ajax the response type to expect, as the response is parsed by the browser before javascript gets a hold of it. 

Here's the above example, configured to treat the response type as text: https://jsbin.com/cajizisexu/edit?html,output
